apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: NodePort
  ports:
    - name: "53"
      port: 53
      targetPort: 53
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/name: pihole