apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale-gateway
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale-gateway
  template:
    metadata:
      labels:
        app: headscale-gateway
    spec:
      serviceAccountName: tailscale
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        imagePullPolicy: Always
        env:
        - name: TS_KUBE_SECRET
          value: "tailscale"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: operator-oauth
              key: ts_authkey
        - name: TS_EXTRA_ARGS
          value: "--login-server https://tailscale.attias.io --advertise-routes=192.168.178.0/24"
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
      volumes:
      - name: tailscale-data
        persistentVolumeClaim:
          claimName: headscale-gw-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-gw-pvc
  namespace: tailscale
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    # Verb 'create' is needed for the initial setup
    verbs: ["create"]
  - apiGroups: [""]
    # Permissions for the specific secret Tailscale uses to store state
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    # This addresses the "not able to write Events" debug message
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io