apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.34.0
    helm:
      releaseName: pihole
      valuesObject:
        DNS1: 9.9.9.9
        DNS2: 1.1.1.1

        persistentVolumeClaim:
          enabled: true
          storageClassName: local-path

        admin:
          # use the secret we just created 
          existingSecret: "pihole-secret"

        serviceDns:
          # combine the TCP and UDP services
          mixedService: true
        
        serviceWeb:
          type: NodePort

        # we won't need that
        serviceDhcp:
          enabled: false

        podDnsConfig:
          enabled: true
          policy: "None"
          nameservers:
          - 127.0.0.1
          - 9.9.9.9