apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.35.0
    helm:
      releaseName: pihole
      valuesObject:
        image:
          repository: pihole/pihole
          tag: 2025.11.1
          pullPolicy: IfNotPresent

        dnsmasq:
          enableCustomDnsMasq: true
          customDnsEntries:
          - address=/pihole.kiki.home/192.168.178.110
          - address=/kiki.node/node.kiki.home/192.168.178.34
          - address=/nas.kiki.home/192.168.178.33
          - address=/offsite.kiki.home/100.114.250.7
          - address=/kiki.server/server.kiki.home/192.168.178.69
          - address=/plex.attias.io/photos.attias.io/overseerr.attias.io/kiki.vps/vps.kiki.home/91.98.236.199
          - address=/traefiknode.attias.io/k0snode.attias.io/argocdnode.attias.io/prometheusnode.attias.io/alertmanagernode.attias.io/192.168.178.103
          - address=/soulsolid.attias.io/obs.attias.io/traefik.attias.io/k0s.attias.io/argocd.attias.io/attias.io/sonarr.attias.io/sabnzbd.attias.io/radarr.attias.io/prowlarr.attias.io/metube.attias.io/www.attias.io/ceph.attias.io/prometheus.attias.io/alertmanager.attias.io/home.attias.io/bazarr.attias.io/tautulli.attias.io/paperless.attias.io/vault.attias.io/recettes.attias.io/budget.attias.io/deemix.attias.io/beets.attias.io/192.168.178.200

        persistentVolumeClaim:
          enabled: true
          storageClass: local-path

        admin:
          existingSecret: "pihole-secret"

        # kubernetes services for web admin
        serviceWeb:
          loadBalancerIP: 192.168.178.110
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        
        # create a kubernetes service and expose
        # port 53 outside of cluster on the local network
        serviceDns:
          mixedService: true
          loadBalancerIP: 192.168.178.110
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
            tailscale.com/expose: "true"
          type: LoadBalancer