apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.34.0
    helm:
      releaseName: pihole
      valuesObject:
        image:
          repository: "pihole/pihole"
          tag: "2025.11.0"
          pullPolicy: IfNotPresent

        persistentVolumeClaim:
          enabled: true
          storageClass: local-path

        admin:
          # use the secret we just created 
          existingSecret: "pihole-secret"

        # will create kubernetes services for web admin
        serviceWeb:
          loadBalancerIP: 192.168.178.34
          type: NodePort
        
        # create a kubernetes service and expose
        # port 53 outside of cluster on the local network
        serviceDns:
          loadBalancerIP: 192.168.178.34
          type: NodePort
          
        # enables cloudflare tunnel sidecar container
        # and sets upstream dns in pihole to leverage it
        doh:
          enabled: true
          pullPolicy: Always
          envVars: {
            DOH_UPSTREAM: "https://1.1.1.1/dns-query"
          }