apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator-kikinode
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts/
    targetRevision: 1.92.4
    helm:
      releaseName: tailscale-operator
      valuesObject:
        oauth:
          # The Client ID the operator will authenticate with.
          clientId:
            valueFrom:
              secretKeyRef:
                name: operator-oauth
                key: client_id
          clientSecret:
            valueFrom:
              secretKeyRef:
                name: operator-oauth
                key: client_secret
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-pod-cidrs-kikinode
  namespace: tailscale
spec:
  replicas: 1
  hostnamePrefix: ts-pod-cidrs-kikinode
  subnetRouter:
    advertiseRoutes:
      - "192.168.0.0/16"
      - "10.244.0.0/24"
      - "10.96.0.0/12"