apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-config-pvc
  namespace: speed
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi